In [1]:
import random

In [2]:
random.random()

0.2138453408907679

In [3]:
random.randint(-10,10)

6

In [4]:
random.randrange(-9,9,2)

5

In [5]:
random.uniform(-10,10)

8.478313914346035

In [8]:
random.randint(-90, 89)+random.random()

-56.32135670031494

In [14]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [15]:
random.randrange(-90, 90, step=1)

57

In [16]:
random.randrange(-90, 90, step=3)

48

In [17]:
random.uniform(-90, 90)

-1.0723656337986682

In [18]:
# Import the NumPy module.
import numpy as np

In [19]:
np.random.uniform(-90.000, 90.000)

-2.2877153752606603

In [20]:
np.random.uniform(low=-90, high=90)

-68.21068184996336

In [21]:
np.random.uniform(-90.000, 90.000, size=50)

array([-32.76965488,  53.65940084,  21.21254789, -20.63448023,
        37.92374208, -10.9266557 ,  -8.39603702, -76.64679807,
        63.9366212 ,   7.20665139, -73.45767138,  69.62659827,
       -42.61205424, -54.63653609,  55.96804619,  45.69550103,
        12.15846566,  18.77486862,  56.63439295, -32.79591011,
        30.48990176, -19.24663815, -80.8906927 ,  80.69721049,
       -78.96284475, -74.08279947,  83.0179801 , -34.63017794,
         9.30731932,  66.58268323, -43.33255814,  12.49706489,
        -6.33299378,   1.55491143,   0.60922957,  37.34464536,
        44.47673665,  10.85027301,  -5.64169504, -26.23046743,
       -74.2776159 ,  23.8841006 ,  75.23854626,  -9.98851032,
       -50.29359351,  53.02969647,  71.18370279,  -0.62498947,
        77.89026194,  62.40581723])

In [22]:
# Import timeit.
import timeit

In [23]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

11.5 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
np.random.uniform(-90.000, 90.000, size=1500)

array([  0.2703848 , -83.52983355,  19.80154592, ...,  -7.30793831,
        11.29068367, -87.03729285])

In [26]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

11.9 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.09 ms ± 36.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
np.random.uniform(-90.000, 90.000, size=1500)

array([-37.52884112,  14.31033389, -47.19794806, ...,  49.65280294,
       -79.01407881, -59.67050437])